apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: appdeploy
        image: stoyankanev/devtask:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: hello-app
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5002
    name: hello-app
  selector:
    app: hello-app
  type: LoadBalancer