name: CD workflow

on:
  # push:
  #   branches:
  #     - main
  release:
    types: [published]
#  pull_request:
#    branches:
#      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: test # must exsist with mentioned secrets below defined
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        #https://github.com/docker/metadata-action/tags
        uses: docker/metadata-action@v4
        with:
          images: stoyankanev/devtask
      
      - name: Build and push Docker image
      # https://github.com/docker/build-push-action/tags
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
